inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/rails'
    - 'bin/spring'
    - 'bin/rake'
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true
